### ISSUE TITLE
Sinhalese Illakkam glyphes in fonts

### ISSUE THREAD

**Issue by Ayesh** [akuru/sinhala-unicode-technical#13]
Are there any fonts from this project that provides glyphes for Sinhalese Illakkam numerals?

U+111E1-U+111F4 codepoints have these:

```json
{
	1: "𑇡",
	2: "𑇢",
	3: "𑇣",
	4: "𑇤",
	5: "𑇥",
	6: "𑇦",
	7: "𑇧",
	8: "𑇨",
	9: "𑇩",
	10: "𑇪",
	20: "𑇫",
	30: "𑇬",
	40: "𑇭",
	50: "𑇮",
	60: "𑇯",
	70: "𑇰",
	80: "𑇱",
	90: "𑇲",
	100: "𑇳",
	1000: "𑇴",
}
```

I was wondering if anyone is planning to work on these code points in any of the Sinhalese Unicode fonts. 

Thanks.

**Comment by pathumego** [comment]
Noto Sans Sinhala and Noto Serif Sinhala already have glyphs encoded for these characters. Abhaya Libre, Maname and Yaldevi fonts will ship these in September.

**Comment by Ayesh** [comment]
This is awesome, thank you.
