### ISSUE TITLE
මෙහෙයුම් පද්ධති සඳහා අනර්ඝ අකුරු මෝස්තරයක් පිළිබඳව සාකච්ඡාව

### ISSUE THREAD

**Issue by aluyama** [akuru/sinhala-unicode-technical#17]
ඉවත් කෙරිණි

**Comment by pathumego** [comment]
@aluyama මේ වසර ගණනාවක් තිස්සේ පවතින අවශ්‍යතාවක්. @mooniak සතුව මේ වෙනුවෙන් දැනට භාවිත කළහැකි රුවකුරු 3ක් තිබෙනවා. මේ සඳහා SIL Open Font License එක භාවිත කලහැකියි ද? නැත්නම් GPL–FE ගැලපෙනවද?

**Comment by aluyama** [comment]
@pathumego පොදුවේ සියළුම වර්ගයේ තාක්‍ෂණික වැඩසටහන් සඳහා ඕනෑම සංවර්ධකයෙකුට, සමාගමකට හෝ වෙනත් පාර්ශ්වයකට කිසිදු බාධාවකින් හෝ විමසීමකින් තොරව නිදහසේ භාවිතයට ගත හැකි බලපත්‍රයක් යටතේ තිබීම ප්‍රමාණවත්. එම රුවකුරු තුන මොනවාද? එවායින් හොඳම රුවකුර කුමක්ද?
