### ISSUE TITLE
Proposal to encode the CANDRABINDU for Sinhala

### ISSUE THREAD

**Issue by pathumego** [akuru/sinhala-unicode-technical#3]
https://www.unicode.org/L2/L2018/18060-sinhala-candrabindu.pdf

**Comment by lianghai** [comment]
Note this proposed character has been approved at UTC \#155: https://www.unicode.org/L2/L2018/18115.htm#155-C22

Act early if you have anything about it to suggest.

**Comment by pathumego** [comment]
SINHALA SIGN CANDRABINDU is encoded at `0D81` in Unicode 13.0  version https://www.unicode.org/charts/PDF/Unicode-13.0/U130-0D80.pdf

**Comment by pathumego** [comment]
Also see https://www.unicode.org/L2/L2018/18079-sinhala-candrabindu.pdf
